"""Report generation — Markdown and PDF exports."""

import io
import datetime
import pandas as pd
from typing import Optional


class ReportService:
    def generate_markdown(
        self,
        title:       str,
        summary:     str,
        findings:    str,
        sql_history: list[dict],
        profile_text: str = "",
    ) -> str:
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        lines = [
            f"# {title}",
            f"*Generated: {now}*",
            "",
            "---",
            "",
            "## Executive Summary",
            summary,
            "",
        ]
        if profile_text:
            lines += ["## Dataset Profile", "```", profile_text, "```", ""]

        if sql_history:
            lines += ["## Analysis History", ""]
            for i, entry in enumerate(sql_history, 1):
                lines += [
                    f"### {i}. {entry.get('question', 'Query')}",
                    "",
                    "**SQL:**",
                    f"```sql\n{entry.get('sql', '')}\n```",
                    "",
                    "**Findings:**",
                    entry.get("analysis", ""),
                    "",
                    "---",
                    "",
                ]
        if findings:
            lines += ["## Additional Findings", findings, ""]

        lines += [
            "---",
            "*Report generated by AI Data Analyst — Powered by Ollama*",
        ]
        return "\n".join(lines)

    def generate_pdf_bytes(self, markdown_text: str) -> Optional[bytes]:
        """Convert markdown to PDF. Returns None if dependencies missing."""
        try:
            import markdown2
            from weasyprint import HTML
            html_body = markdown2.markdown(markdown_text, extras=["tables", "fenced-code-blocks"])
            full_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Helvetica', sans-serif; color: #1a1a2e; padding: 40px; line-height: 1.6; }}
  h1 {{ color: #0a2540; border-bottom: 3px solid #00d4ff; padding-bottom: 12px; }}
  h2 {{ color: #0a2540; margin-top: 32px; }}
  h3 {{ color: #334155; }}
  code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-size: 0.85em; }}
  pre  {{ background: #f1f5f9; padding: 16px; border-radius: 8px; overflow-x: auto; }}
  table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
  th, td {{ border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }}
  th {{ background: #0a2540; color: white; }}
  hr {{ border: 1px solid #e2e8f0; margin: 24px 0; }}
</style>
</head>
<body>{html_body}</body>
</html>"""
            pdf = HTML(string=full_html).write_pdf()
            return pdf
        except ImportError:
            return None
